name: Fitbit Debug
on:
  workflow_dispatch:

jobs:
  dump_fitbit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install requests
      - name: Run debug
        run: python3 cortex_debug.py
        env:
          FITBIT_CLIENT_ID: ${{ secrets.FITBIT_CLIENT_ID }}
          FITBIT_CLIENT_SECRET: ${{ secrets.FITBIT_CLIENT_SECRET }}
          FITBIT_REFRESH_TOKEN: ${{ secrets.FITBIT_REFRESH_TOKEN }}
